server:
  port: 4001
spring:
  application:
    name: cucumberspringtest
#  zipkin:
#    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://192.168.137.201:3306/control_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Abc123#456
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    minIdle: 1
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    test-on-return: false
    test-on-borrow: false
    test-while-idle: true
    validation-query: select 'x'
    min-evictable-idle-time-millis: 300000
    time-between-eviction-runs-millis: 60000
    max-active: 20
    max-wait: 60000
    initial-size: 1
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.137.201
    port: 6379
    password: Abc123#456
    database: 1
    timeout: 60s
    jedis:
      pool:
        max-idle: 50
        min-idle: 5
        max-wait: -1s
        max-active: -1
  transaction:
    rollback-on-commit-failure: true

#mybatis中pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#mybatis通用mapper
mapper:
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
  #设置insert和update中，是否判断字符串类型!=''
  not-empty: true
  #枚举按简单类型处理
  enum-as-simple-type: true
